---
Name: goldfinch-search
---
Goldfinch\Search\Search:
  searchable_pagination: 10 # false / (numeric)
  # searchable_limit_items: false
  searchable:
    # - App\Models\My_Custom_model.php


---
Name: goldfinch-search-icon
Only:
  moduleexists: 'goldfinch/enchantment'
---

Goldfinch\Search\Search:
  icon_class: 'bi-file-earmark-easel-fill'
